name: Run Robot Framework Tests
on: [push]  # event that triggers the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker container
      run: docker build -t robot-tests .
    - name: Run Robot Framework tests
      run: docker run -v ${{ github.workspace }}/logs:/app/logs robot-tests
    - name: Upload Robot Framework logs
      uses: actions/upload-artifact@v4
      with:
        name: robot-logs
        path: logs/
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install beautifulsoup4
    - name: Analyze HTML logs
      run: python scripts/parse_logs.py